version: 2.1

jobs:
  build-builder:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Builder App
          command: ./.circleci/install-builder.sh
#      - persist_to_workspace:
#          root: ./
#          paths: /home/circleci/.local/bin/energy-tracker-build

  build-api:
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: (cd api; npm install)
      - persist_to_workspace:
          root: ./
          paths: ./api

  deploy-api: &DEPLOY_API
      docker:
        - image: cimg/node:15.6.0
      steps:
        - checkout
        - attach_workspace:
            at: /workspace
        - run:
            name: Deploy API
            command: (cd /workspace/api; /workspace/energy-tracker-build deploy-api --env=$ENV)

  deploy-api-dev:
    <<: *DEPLOY_API
    environment:
      ENV: dev

workflows:
  app:
    jobs:
      - build-builder:
        filters:
            branches:
              only: ci-test
      - build-api:
          requires:
            - build-builder
      - deploy-api-dev:
          requires:
            - build-api
